name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    defaults:
      run:
        working-directory: ./spring-boot-spring-security-jwt-authentication
jobs:
  build_and_push:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        uses: docker/build-push-action@v3
      - run: mv -f spring-boot-spring-security-jwt-authentication/* .
        with:
          context: ./spring-boot-spring-security-jwt-authentication
          push: true
          tags: maelpj/algoplusv1:backend

  deploy_to_droplet:
    runs-on: ubuntu-latest
    needs: build_and_push
    name: Deploy to Droplet
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /alogplus
            docker-compose stop 
            docker rm backend
            docker pull maelpj/algoplusv1:backend:latest
            docker-compose up -d 
            docker ps -a
